import { useState, useEffect, useCallback } from 'react';
import { createClientComponentClient } from '@/lib/supabase/client';
import { useAuth } from './useAuth';
import toast from 'react-hot-toast';
import type { EventData } from '@/types';

interface DatabaseEvent extends EventData {
  id: string;
  user_id: string;
  share_id?: string;
  created_at: string;
  updated_at?: string;
  last_used_at?: string;
}

interface UsageData {
  events_created: number;
  user_id: string;
  month: string;
}

interface UseRecentEventsReturn {
  events: DatabaseEvent[];
  loading: boolean;
  deleteEvent: (eventId: string) => Promise<boolean>;
  duplicateEvent: (eventId: string) => Promise<DatabaseEvent>;
  refetch: () => Promise<void>;
}

export function useRecentEvents(): UseRecentEventsReturn {
  const [events, setEvents] = useState<DatabaseEvent[]>([]);
  const [loading, setLoading] = useState<boolean>(true);
  const { user } = useAuth();
  const supabase = createClientComponentClient();

  const fetchRecentEvents = useCallback(async (): Promise<void> => {
    try {
      setLoading(true);
      const { data, error } = await supabase
        .from('events')
        .select('*')
        .eq('user_id', user?.id)
        .order('last_used_at', { ascending: false })
        .limit(5);

      if (error) throw error;
      setEvents(data || []);
    } catch (error) {
      console.error('Error fetching recent events:', error);
      toast.error('Failed to load recent events');
    } finally {
      setLoading(false);
    }
  }, [user, supabase]);

  useEffect(() => {
    if (user) {
      fetchRecentEvents();
    } else {
      setEvents([]);
      setLoading(false);
    }
  }, [user, fetchRecentEvents]);

  const deleteEvent = async (eventId: string): Promise<boolean> => {
    try {
      const { error } = await supabase
        .from('events')
        .delete()
        .eq('id', eventId)
        .eq('user_id', user?.id);

      if (error) throw error;

      setEvents(events.filter(event => event.id !== eventId));
      return true;
    } catch (error) {
      console.error('Error deleting event:', error);
      throw error;
    }
  };

  const duplicateEvent = async (eventId: string): Promise<DatabaseEvent> => {
    try {
      const eventToDuplicate = events.find(event => event.id === eventId);
      if (!eventToDuplicate) throw new Error('Event not found');

      // Build the insert payload explicitly from DB columns. The previous
      // version checked the nonexistent `usage_tracking` table (every attempt
      // threw on the missing-table error code) and spread the whole row,
      // carrying the original `id` into the insert (primary-key conflict).
      const row = eventToDuplicate as unknown as Record<string, unknown>;
      const { title, description, location, organizer } = eventToDuplicate;
      const now = new Date().toISOString();
      const duplicatedEvent = {
        title: `${title} (Copy)`,
        description,
        location,
        organizer,
        start_date: row.start_date,
        start_time: row.start_time,
        end_date: row.end_date,
        end_time: row.end_time,
        timezone: row.timezone,
        is_all_day: row.is_all_day ?? false,
        is_recurring: row.is_recurring ?? false,
        recurrence_rule: row.recurrence_rule ?? null,
        user_id: user?.id,
        created_at: now,
        updated_at: now
        // share_id auto-generated by the database
      };

      const { data: newEvent, error } = await supabase
        .from('events')
        .insert([duplicatedEvent])
        .select()
        .single();

      if (error) throw error;

      await fetchRecentEvents();
      return newEvent as DatabaseEvent;
    } catch (error) {
      console.error('Error duplicating event:', error);
      throw error;
    }
  };

  return {
    events,
    loading,
    deleteEvent,
    duplicateEvent,
    refetch: fetchRecentEvents
  };
}