import { NextRequest, NextResponse } from 'next/server';
import { createServiceRoleClient, requireAuth } from '@/lib/supabase/server';
import { randomBytes } from 'crypto';

/**
 * Generates a URL-safe slug from a title string.
 *
 * Steps:
 *   1. Lowercase the title
 *   2. Replace any run of non-alphanumeric characters with a single hyphen
 *   3. Strip leading/trailing hyphens
 *   4. Append a 4-character random suffix to reduce collision probability
 *
 * Examples:
 *   "Product Launch 2026!" → "product-launch-2026-a3b4"
 *   "  Hello  World  "    → "hello-world-x9z2"
 */
function slugify(title: string): string {
  const base = title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 60); // cap base length so full slug stays under 65 chars

  const suffix = randomBytes(2).toString('hex'); // 4 hex chars
  return `${base}-${suffix}`;
}

/**
 * POST /api/event-pages
 *
 * Creates a new event page (draft) for the authenticated user.
 *
 * Request body:
 *   title       string  required
 *   description string  optional
 *   location    string  optional
 *   timezone    string  required (IANA, e.g. "America/New_York")
 *   startAt     string  optional (ISO 8601)
 *   endAt       string  optional (ISO 8601)
 *   isAllDay    boolean optional (default false)
 *   slug        string  optional — auto-generated from title if omitted
 *
 * Response 200:
 *   { id, slug, feedToken, eventPageUrl }
 *
 * Error responses:
 *   401 — not authenticated
 *   400 — missing required fields
 *   409 — slug already taken (only if caller supplied a slug)
 *   500 — database error
 */
export async function POST(request: NextRequest) {
  try {
    // Authenticate
    const user = await requireAuth(request);

    // Parse body
    let body: {
      title?: string;
      description?: string;
      location?: string;
      timezone?: string;
      startAt?: string;
      endAt?: string;
      isAllDay?: boolean;
      slug?: string;
    };

    try {
      body = await request.json();
    } catch {
      return NextResponse.json(
        { error: 'Invalid JSON body' },
        { status: 400 }
      );
    }

    // Validate required fields
    const { title, description, location, timezone, startAt, endAt, isAllDay, slug: suppliedSlug } = body;

    if (!title || typeof title !== 'string' || title.trim().length === 0) {
      return NextResponse.json(
        { error: 'title is required' },
        { status: 400 }
      );
    }

    if (!timezone || typeof timezone !== 'string' || timezone.trim().length === 0) {
      return NextResponse.json(
        { error: 'timezone is required' },
        { status: 400 }
      );
    }

    const supabase = createServiceRoleClient();

    // Determine slug — supplied or auto-generated
    let slug: string;

    if (suppliedSlug && typeof suppliedSlug === 'string' && suppliedSlug.trim().length > 0) {
      // Validate caller-supplied slug: lowercase alphanumeric + hyphens only
      const cleanSlug = suppliedSlug.trim().toLowerCase();
      if (!/^[a-z0-9-]+$/.test(cleanSlug)) {
        return NextResponse.json(
          { error: 'slug may only contain lowercase letters, numbers, and hyphens' },
          { status: 400 }
        );
      }

      // Check uniqueness
      const { data: existing } = await supabase
        .from('event_pages')
        .select('id')
        .eq('slug', cleanSlug)
        .maybeSingle();

      if (existing) {
        return NextResponse.json(
          { error: 'slug is already taken' },
          { status: 409 }
        );
      }

      slug = cleanSlug;
    } else {
      // Auto-generate with collision retry (up to 5 attempts)
      let generated = '';
      let unique = false;
      let attempts = 0;

      while (!unique && attempts < 5) {
        generated = slugify(title);
        const { data: existing } = await supabase
          .from('event_pages')
          .select('id')
          .eq('slug', generated)
          .maybeSingle();

        if (!existing) {
          unique = true;
        }
        attempts++;
      }

      if (!unique) {
        return NextResponse.json(
          { error: 'Failed to generate a unique slug. Please supply one explicitly.' },
          { status: 500 }
        );
      }

      slug = generated;
    }

    // Insert the event page — feed_token is generated by the DB default (gen_random_uuid())
    const { data, error } = await supabase
      .from('event_pages')
      .insert({
        user_id: user.id,
        slug,
        title: title.trim(),
        description: description?.trim() ?? null,
        location: location?.trim() ?? null,
        timezone: timezone.trim(),
        start_at: startAt ?? null,
        end_at: endAt ?? null,
        is_all_day: isAllDay ?? false,
        is_published: false,
      })
      .select('id, slug, feed_token')
      .single();

    if (error) {
      console.error('[event-pages] DB insert error:', error);
      return NextResponse.json(
        { error: 'Failed to create event page' },
        { status: 500 }
      );
    }

    const baseUrl = process.env.NEXT_PUBLIC_BASE_URL ?? 'https://punktual.co';

    return NextResponse.json({
      id: data.id,
      slug: data.slug,
      feedToken: data.feed_token,
      eventPageUrl: `/e/${data.slug}`,
    });

  } catch (error) {
    console.error('[event-pages] Unexpected error:', error);

    if (error instanceof Error && error.message.includes('Authentication')) {
      return NextResponse.json(
        { error: 'Authentication required' },
        { status: 401 }
      );
    }

    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}
